### ISSUE TITLE
inclusion_check.py  shows debuginfo not enough

### ISSUE THREAD

**Issue by ghost** [blade-build/blade-build#953]
**Is your feature request related to a problem? Please describe.**
a lot of failure occured when i build my project

Blade(error): Blade build tool cc_inclusion_check error:  Traceback (most recent call last):
  File "xxx/blade-build-2.0/src/blade/builtin_tools.py", line 599, in main
    exit_code = _BUILTIN_TOOLS[name](args=args, **options)
  File "xxx/blade-build-2.0/src/blade/builtin_tools.py", line 117, in generate_cc_inclusion_check
    ok, details = inclusion_check.check(info_file)
  File "xxx/blade-build-2.0/src/blade/inclusion_check.py", line 399, in check
    return checker.check()
  File "xxx/blade-build-2.0/src/blade/inclusion_check.py", line 371, in check
    check_file(src, full_src, is_header=False)
  File "xxx/blade-build-2.0/src/blade/inclusion_check.py", line 352, in check_file
    direct_hdrs, stacks = _parse_inclusion_stacks(path, self.build_dir)
  File "xxx/blade-build-2.0/src/blade/inclusion_check.py", line 132, in _parse_inclusion_stacks
    assert level == current_level + 1
AssertionError

no idea what they are talking about~~~~~
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chen3feng** [comment]
Can you kindly provide a minimal reproducible code set? thanks.

You can modify the source code, add more information in the assert statement,

```python
assert level == current_level + 1, path
```

See
https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement
for help.

**Comment by chen3feng** [comment]
You can upload the problematic file as a attachment when you get its path by this way.

**Comment by kuafu-run** [comment]
[3897/6946] CXX ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.cpp
 build64_release/ads/proto/enums/creative_screen_type.pb.h
 /usr/include/google/protobuf/port_undef.inc
 /usr/include/boost/date_time/date_generator_formatter.hpp
 /usr/include/google/protobuf/port_def.inc
 /usr/include/boost/container/detail/config_end.hpp
 /usr/include/bits/fcntl.h
 /usr/include/boost/interprocess/detail/config_end.hpp
 /usr/include/boost/interprocess/detail/config_begin.hpp
 /usr/include/boost/assert.hpp
 /usr/include/boost/container/detail/destroyers.hpp
 /usr/include/boost/type_traits/has_greater.hpp
 /usr/include/boost/type_traits/detail/bool_trait_undef.hpp
 /usr/include/boost/range/distance.hpp
 /usr/include/boost/concept/usage.hpp
 /usr/include/boost/preprocessor/seq/elem.hpp
 /usr/include/google/protobuf/port_undef.inc
 /usr/include/google/protobuf/port_undef.inc
[3898/6946] CXX ads/serving/exchange/handler/redis_service.cpp
[3899/6946] CC INCLUSION CHECK build64_release/ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.incchk
FAILED: build64_release/ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.incchk.result 
PYTHONPATH=/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src:$PYTHONPATH /usr/bin/python -m blade.builtin_tools cc_inclusion_check build64_release/ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.incchk.result build64_release/ads/serving/dsp_show/dsp_retrieve/pipeline/flow_select/policy/special_user_flow_select.incchk
Blade(error): Blade build tool cc_inclusion_check error:  Traceback (most recent call last):
  File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/builtin_tools.py", line 599, in main
    exit_code = _BUILTIN_TOOLS[name](args=args, **options)
  File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/builtin_tools.py", line 117, in generate_cc_inclusion_check
    ok, details = inclusion_check.check(info_file)
  File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 399, in check
    return checker.check()
  File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 371, in check
    check_file(src, full_src, is_header=False)
  File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 352, in check_file
    direct_hdrs, stacks = _parse_inclusion_stacks(path, self.build_dir)
  File "/data/gitlab-runner-build/65d19821/0/adssrv/ads_serving/blade-build-2.0-beta2/src/blade/inclusion_check.py", line 132, in _parse_inclusion_stacks
    assert level == current_level + 1
AssertionError

**Comment by noanswer** [comment]
https://github.com/chen3feng/blade-build/blob/77bbb058455f493e892e8bae1bd3015e6a42cba4/src/blade/inclusion_check.py#L133C17-L142C49

With the console error, you can find why the assert raise

**Comment by chen3feng** [comment]
Root cause, for the record.

The `.incstk` filter is **path-based, not semantic**: it drops headers whose resolved path is **absolute** and keeps **relative** ones (GCC awk `/^\.+ [^\/]/`; MSVC `not isabs or in_workspace`), and `_parse_inclusion_stacks` itself ignores `os.path.isabs(hdr)`. It has no notion of "system header."

So a depth gap does **not** come from a normal system subtree (those are entirely absolute → fully filtered → contiguous, no gap). It requires **a header resolved via an absolute path to include a header resolved via a relative path**, e.g. with mixed include flags: a third-party header reached via an absolute `-I/-isystem` does `#include "project_config.h"`, which is found via the project's relative `-I` → kept. The incstk then jumps from the absent absolute parent (level N) to the kept relative child (level N+1 shown as a deeper level), and the old `assert level == current_level + 1` aborted the build.

Why only *absolute* parents cause it: a relative skip-point (a generated `build64_release/*.pb.h`) is *present* in the incstk, so it sets `skip_level` and its subtree gets skipped cleanly. An absolute header is *absent*, so it never sets `skip_level`, and its kept child lands ≥2 levels deep — the gap.

In practice this means a project header was pulled in *through* a system/absolute-path include tree — almost always an accidental `-I`/`-isystem` wiring mistake (a project header injected into a vendored/system tree). It is rare and graph-dependent, which is why the original failures looked "random."

Fix (#1200): treat a forward gap like an absolute-header subtree — skip it (it's transitive, reached only through an untracked absolute header) instead of crashing. It cannot mask a missing *direct* dependency: a gap needs `level >= 2`, while level-1 direct includes are recorded before the gap branch and never trigger it.
